### ISSUE TITLE
您好，关于由mask生成对应的原图的模型是使用全部标签来训练的pixel2pixel网络的吗

### ISSUE THREAD

**Issue by userhr2333** [FeiLyu/SASSL#1]
您好，有一个疑问，这里的pixel2pixel网络使用的是所有的标签（也即使用原图和已经标注的mask来训练pixel2pixel网络）训练出来的吗？

**Comment by FeiLyu** [comment]
您好，synthesis使用的是与segmentation相同的有label的数据进行训练。例如，10%有标签数据用于segmentation，那么就用这10%的数据用于训练synthesis model。

如果还有疑问，欢迎随时联系。

**Comment by debuluoyizhe** [comment]
您好，我在训练train_SACPS.py时候，发现没有MOS1000_net_G.pth预训练模型，FileNotFoundError: [Errno 2] No such file or directory: 'MOS1000_net_G.pth’，请问需要用到这个文件吗

**Comment by FeiLyu** [comment]
> 您好，我在训练train_SACPS.py时候，发现没有MOS1000_net_G.pth预训练模型，FileNotFoundError: [Errno 2] No such file or directory: 'MOS1000_net_G.pth’，请问需要用到这个文件吗

您好，你可以自己train SEAN模型following: https://github.com/ZPdesu/SEAN , 或者使用我们train好的checkpoints: https://drive.google.com/file/d/1X4zWK5fV16ZRT7R55wCiyBFzat_9Lz1s/view

**Comment by debuluoyizhe** [comment]
非常感谢您的回复！不过有些预训练的细节我还是没有弄明白，可以把预训练的code公开一下吗，非常感谢！

**Comment by FeiLyu** [comment]
> 
pretrain的代码直接使用SEAN模型: https://github.com/ZPdesu/SEAN，请参照SEAN准备数据及训练。如果还有训练细节有问题，欢迎随时email给我。

**Comment by debuluoyizhe** [comment]
曹稀哲
***@***.***

非常感谢您的回复！

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FeiLyu/SASSL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月14日(星期三) 下午2:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FeiLyu/SASSL] 您好，关于由mask生成对应的原图的模型是使用全部标签来训练的pixel2pixel网络的吗 (Issue #1)





   
pretrain的代码直接使用SEAN模型: https://github.com/ZPdesu/SEAN，请参照SEAN准备数据及训练。如果还有训练细节有问题，欢迎随时email给我。

**Comment by debuluoyizhe** [comment]
作者您好，我想训练一个256*256的SASSL模型，我先利用SEAN预训练好了预训练模型，之后放入SASSL模型后，报错RuntimeError: Error(s) in loading state_dict for SPADEGenerator:
	size mismatch for Zencoder.model.14.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for Zencoder.model.14.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]). 我需要怎样改Encoder的参数，非常感谢！

**Comment by debuluoyizhe** [comment]
作者您好，我想训练一个256*256的SASSL模型，我先利用SEAN预训练好了预训练模型，之后放入SASSL模型后，报错RuntimeError: Error(s) in loading state_dict for SPADEGenerator:
size mismatch for Zencoder.model.14.weight: copying a param with shape torch.Size([512, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
size mismatch for Zencoder.model.14.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]). 有没有可以直接设置的参数，或者我怎样改Encoder的参数，非常感谢！

**Comment by debuluoyizhe** [comment]
感谢老铁！！终于调通了，nice work

**Comment by FeiLyu** [comment]
> 感谢老铁！！终于调通了，nice work

太棒啦！
