### ISSUE TITLE
I have encountered some issues and hope to be answered，What should I do to solve this situation？

### ISSUE THREAD

**Issue by coderque** [FeiLyu/SASSL#2]
![image](https://user-images.githubusercontent.com/128224865/226540664-6e7f40fa-af2b-4666-a4fd-24ea9a8de87e.png)

**Comment by FeiLyu** [comment]
> ![image](https://user-images.githubusercontent.com/128224865/226540664-6e7f40fa-af2b-4666-a4fd-24ea9a8de87e.png)

Hi, thanks for your interest in our work. I think you may need to check the values of these three variables: alpha, style_codes, and extras_codes, to see which one has an abnormal value.
