### ISSUE TITLE
关于SEAN模型训练的问题

### ISSUE THREAD

**Issue by swaggypg** [FeiLyu/SASSL#3]
非常感谢您与团队对半监督医学图像分割社区做出的贡献，我从这篇论文中受益良多，在实现时我有一个疑问，就是您给出了C249数据集三种不同的标记数据率情况下对应的SEAN模型，那在训练时是分别只使用10%、20%、30%的数据去训练出一个SEAN模型吗？SEAN模型是否对于数据的格式有要求呢，如果我的数据集格式为h5，是否要重写它代码中的dataloader呢？望回复，万分感谢！

**Comment by FeiLyu** [comment]
非常感谢您对我们工作的认可！

> 训练时是分别只使用10%、20%、30%的数据去训练出一个SEAN模型吗
--Reply： 是的，因为要与semi-supervised setting保持一致。

>SEAN模型是否对于数据的格式有要求呢
--Reply：您可以参考：https://github.com/ZPdesu/SEAN ， 目前我是follow他们的setting使用的是PNG格式的图片，您可以考虑是否将h5格式转成png。

希望可以解答您的问题，如果还有问题，欢迎随时联系交流！
